namespace LLMThinkTank.Core.Models;

/// <summary>
/// Represents a single entry in the application-wide diagnostic log.
/// Entries capture API calls, status changes, and errors for real-time display
/// in the log panel, enabling users to troubleshoot provider connectivity issues.
/// </summary>
/// <param name="Timestamp">UTC timestamp when the event occurred.</param>
/// <param name="Source">Identifier of the originating component (e.g., provider ID or "system").</param>
/// <param name="Text">Human-readable log message or redacted API response.</param>
/// <param name="IsError">Whether this entry represents an error condition.</param>
public record ChatLogEntry(DateTimeOffset Timestamp, string Source, string Text, bool IsError = false);

/// <summary>
/// A single conversation turn stored on disk as part of a chat's JSON history.
/// Used to reconstruct conversation state when loading persisted conversations.
/// </summary>
/// <param name="ParticipantId">Unique identifier of the participant who produced this turn.</param>
/// <param name="Text">The response text generated by the AI model.</param>
/// <param name="Round">Zero-based discussion round number this turn belongs to.</param>
/// <param name="IsError">Whether this turn represents a failed API call rather than a valid response.</param>
public sealed record PersistedTurn(string ParticipantId, string Text, int Round, bool IsError);
