<#
.SYNOPSIS
  Codex documentation tooling for Think Tank (TT).
.DESCRIPTION
  Subcommands:
    doctor  - validate the docs/ canon (front-matter, unique ids, cross-refs, schemas,
              test tokens, cited paths, generated-artifact freshness). Exit non-zero on hard error.
    digest  - regenerate docs/BIBLE.digest.md from BIBLE.md sections 1, 3, 5, 9 + a status index.
  Windows PowerShell 5.1 safe. No build step.
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet('doctor', 'digest')]
  [string]$Command = 'doctor'
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$DocsDir  = Join-Path $RepoRoot 'docs'
$Bible    = Join-Path $DocsDir 'BIBLE.md'
$Stories  = Join-Path $DocsDir 'USER_STORIES.md'
$Amend    = Join-Path $DocsDir 'AMENDMENTS.md'
$Digest   = Join-Path $DocsDir 'BIBLE.digest.md'

# ---------- helpers ----------
function Read-Text([string]$path) { [IO.File]::ReadAllText($path) }

function Get-FrontMatter([string]$text) {
  # returns hashtable of key->value for a leading --- ... --- block, or $null
  $text = $text.TrimStart([char]0xFEFF)
  $lines = [regex]::Split($text, "\r?\n")
  if ($lines.Count -lt 1 -or $lines[0].Trim() -ne '---') { return $null }
  $fm = @{}
  for ($i = 1; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -eq '---') { return $fm }
    if ($lines[$i] -match '^\s*([A-Za-z_]+)\s*:\s*(.+?)\s*$') { $fm[$Matches[1]] = $Matches[2] }
  }
  return $null  # no closing fence
}

function Get-AnchorIds([string]$text) {
  # explicit {#id} anchors; § is the section sign used in TT-section anchors
  [regex]::Matches($text, '\{#([A-Za-z0-9_.\u00A7\-]+)\}') | ForEach-Object { $_.Groups[1].Value }
}

function Get-AnchorRefs([string]$text) {
  # markdown links to (...#id) and (file#id); § is the section sign
  [regex]::Matches($text, '\]\(([^)]*#[A-Za-z0-9_.\u00A7\-]+)\)') | ForEach-Object { $_.Groups[1].Value }
}

$script:Errors   = @()
$script:Warnings = @()
$script:Checks   = @()
function Fail($m)  { $script:Errors   += $m; $script:Checks += "  [FAIL] $m" }
function Warn($m)  { $script:Warnings += $m; $script:Checks += "  [warn] $m" }
function Pass($m)  { $script:Checks += "  [ ok ] $m" }

# ---------- DIGEST ----------
function Get-Section([string]$text, [int]$n) {
  # returns the body of "## N. Title {#...}" up to the next "## N." heading or EOF
  $pattern = '(?ms)^##\s+' + $n + '\.\s.*?(?=^##\s+\d+\.|\z)'
  $m = [regex]::Match($text, $pattern)
  if ($m.Success) { return $m.Value.TrimEnd() }
  return ''
}

function Invoke-Digest {
  if (-not (Test-Path $Bible)) { Fail "docs/BIBLE.md not found"; return }
  $text = Read-Text $Bible
  $fm = Get-FrontMatter $text
  $proj = if ($fm) { $fm['project'] } else { 'Think Tank' }

  $s1 = Get-Section $text 1
  $s3 = Get-Section $text 3
  $s5 = Get-Section $text 5
  $s9 = Get-Section $text 9

  # status index from USER_STORIES.md
  $done = 0; $partial = 0; $planned = 0; $cut = 0
  if (Test-Path $Stories) {
    $st = Read-Text $Stories
    # astral-plane emoji are surrogate pairs; build them via code point, not [char]
    $emCheck   = [char]::ConvertFromUtf32(0x2705)    # check mark (BMP)
    $emPartial = [char]::ConvertFromUtf32(0x1F7E1)   # yellow circle
    $emPlanned = [char]::ConvertFromUtf32(0x2B1C)    # white square (BMP)
    $emCut     = [char]::ConvertFromUtf32(0x1F5D1)   # wastebasket
    # only count actual story lines (those bearing a TT-US- id), not the legend/blockquote
    $storyText = (([regex]::Split($st, "\r?\n")) | Where-Object { $_ -match 'TT-US-' }) -join "`n"
    $done    = ([regex]::Matches($storyText, [regex]::Escape($emCheck))).Count
    $partial = ([regex]::Matches($storyText, [regex]::Escape($emPartial))).Count
    $planned = ([regex]::Matches($storyText, [regex]::Escape($emPlanned))).Count
    $cut     = ([regex]::Matches($storyText, [regex]::Escape($emCut))).Count
  }

  # latest amendment head
  $amendHead = ''
  if (Test-Path $Amend) {
    $am = Read-Text $Amend
    $matches = [regex]::Matches($am, '(?m)^##\s+(TT-A\d+.*)$')
    if ($matches.Count -gt 0) { $amendHead = $matches[$matches.Count - 1].Groups[1].Value.Trim() }
  }

  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("AUTHORITATIVE - full detail in docs/BIBLE.md")
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("# $proj - Codex Digest (generated)")
  [void]$sb.AppendLine("<!-- generatedFrom: TT-BIBLE -->")
  [void]$sb.AppendLine("> Regenerated by tools/codex.ps1 digest. Do not hand-edit.")
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine($s1); [void]$sb.AppendLine("")
  [void]$sb.AppendLine($s3); [void]$sb.AppendLine("")
  [void]$sb.AppendLine($s5); [void]$sb.AppendLine("")
  [void]$sb.AppendLine($s9); [void]$sb.AppendLine("")
  [void]$sb.AppendLine("## Status index")
  [void]$sb.AppendLine("- done: $done  |  partial: $partial  |  planned: $planned  |  cut: $cut")
  [void]$sb.AppendLine("- latest amendment: $amendHead")
  [void]$sb.AppendLine("")

  [IO.File]::WriteAllText($Digest, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
  Write-Host "digest -> docs/BIBLE.digest.md (done=$done partial=$partial planned=$planned cut=$cut)"
}

# ---------- DOCTOR ----------
function Invoke-Doctor {
  if (-not (Test-Path $DocsDir)) { Fail "docs/ not found"; return }

  $canon = @()
  foreach ($f in @($Bible, $Stories, $Amend)) { if (Test-Path $f) { $canon += $f } }
  $canon += (Get-ChildItem -Path (Join-Path $DocsDir 'rfc') -Filter '*.md' -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName })
  $dataDir = Join-Path $DocsDir 'data'
  $jsonFiles = @()
  if (Test-Path $dataDir) { $jsonFiles = Get-ChildItem -Path $dataDir -Filter '*.json' -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch '_schema' } }

  # 1) front-matter
  foreach ($f in $canon) {
    $fm = Get-FrontMatter (Read-Text $f)
    $rel = $f.Replace($RepoRoot, '').TrimStart('\','/')
    if (-not $fm) { Fail "$rel - missing/invalid codex front-matter" }
    elseif (-not $fm['codex'] -or -not $fm['layer'] -or -not $fm['updated']) { Fail "$rel - front-matter missing required keys (codex/layer/updated)" }
    else { Pass "$rel front-matter" }
  }

  # 2) unique anchor ids across canon + every ref resolves
  $allIds = @{}
  foreach ($f in $canon) {
    foreach ($id in (Get-AnchorIds (Read-Text $f))) {
      if ($allIds.ContainsKey($id)) { Fail "duplicate anchor id {#$id}" } else { $allIds[$id] = $f }
    }
  }
  if ($script:Errors.Count -eq 0) { Pass "$($allIds.Count) anchor ids unique" }

  foreach ($f in $canon) {
    foreach ($ref in (Get-AnchorRefs (Read-Text $f))) {
      $id = ($ref -split '#')[-1]
      if (-not $allIds.ContainsKey($id)) { Fail "$([IO.Path]::GetFileName($f)) -> unresolved cross-ref #$id" }
    }
  }
  if ($script:Errors.Count -eq 0) { Pass "all #anchor cross-refs resolve" }

  # 3) JSON data validates id-uniqueness (schema presence) - none expected for an app
  if ($jsonFiles.Count -eq 0) { Pass "no L5 data files (app domain)" }
  else {
    $ids = @{}
    foreach ($j in $jsonFiles) {
      $schema = Join-Path (Join-Path $dataDir '_schema') ("{0}.schema.json" -f ([IO.Path]::GetFileNameWithoutExtension($j.Name)))
      if (-not (Test-Path $schema)) { Warn "no _schema for data file $($j.Name)" }
      try { $obj = (Read-Text $j.FullName) | ConvertFrom-Json } catch { Fail "$($j.Name) - invalid JSON"; continue }
      foreach ($e in @($obj)) { if ($e.id) { if ($ids.ContainsKey($e.id)) { Fail "duplicate entity id $($e.id)" } else { $ids[$e.id] = $true } } }
    }
    Pass "$($jsonFiles.Count) data file(s) checked"
  }

  # 4) every checked story names a test token; best-effort existence in test tree
  if (Test-Path $Stories) {
    $st = Read-Text $Stories
    $check = [char]0x2705
    $testTree = Get-ChildItem -Path $RepoRoot -Filter '*.cs' -Recurse -ErrorAction SilentlyContinue |
                Where-Object { $_.FullName -match 'Tests' -and $_.FullName -notmatch '\\(bin|obj)\\' }
    $testText = ($testTree | ForEach-Object { Read-Text $_.FullName }) -join "`n"
    # split into per-story blocks at each "**TT-US-" marker so multi-line stories keep their citation
    $blocks = [regex]::Split($st, '(?=\*\*TT-US-)') | Where-Object { $_ -match '^\*\*TT-US-' }
    foreach ($block in $blocks) {
      # only checked (done) stories must cite a test
      $marker = [regex]::Match($block, '\*\*TT-US-[A-Za-z0-9]+\s*(.)')
      $isDone = $block -match ('\*\*TT-US-[A-Za-z0-9]+\s*' + [regex]::Escape($check))
      $usId = ([regex]::Match($block, 'TT-US-[A-Za-z0-9]+')).Value
      if (-not $isDone) { continue }
      # citation tokens are the part of the block before the next story (cut at a double newline gap is unnecessary; Split already isolates)
      $tokens = [regex]::Matches($block, '`([A-Za-z_][A-Za-z0-9_]+)`') | ForEach-Object { $_.Groups[1].Value }
      $cited = $tokens | Where-Object { $_ -match '_' }   # test method names contain underscores
      if ($cited.Count -eq 0) { Fail "story $usId is done but cites no test token" }
      else {
        foreach ($t in $cited) { if ($testText -notmatch [regex]::Escape($t)) { Warn "story $usId cites '$t' not found in test tree" } }
      }
    }
    if ($script:Errors.Count -eq 0) { Pass "every checked story cites a test" }
  }

  # 5) every code path/file cited in the bible exists on disk
  if (Test-Path $Bible) {
    $bt = Read-Text $Bible
    $paths = [regex]::Matches($bt, '`(ThinkTank\.[A-Za-z]+(?:/[A-Za-z0-9_.\-]+)+\.(?:cs|csproj|razor|json|css|js))`') | ForEach-Object { $_.Groups[1].Value } | Select-Object -Unique
    foreach ($p in $paths) {
      $full = Join-Path $RepoRoot ($p -replace '/', '\')
      if (-not (Test-Path $full)) { Fail "bible cites missing path: $p" }
    }
    if ($paths.Count -gt 0 -and $script:Errors.Count -eq 0) { Pass "$($paths.Count) cited code path(s) exist" }
  }

  # 6) generatedFrom freshness: digest must be >= bible mtime
  if (Test-Path $Digest) {
    if ((Get-Item $Bible).LastWriteTimeUtc -gt (Get-Item $Digest).LastWriteTimeUtc) {
      Fail "docs/BIBLE.digest.md is stale (BIBLE.md changed after it) - run 'codex.ps1 digest'"
    } else { Pass "digest is fresh (generatedFrom TT-BIBLE)" }
  } else { Warn "docs/BIBLE.digest.md missing - run 'codex.ps1 digest'" }

  # 7) regenerate a shadow digest and warn if the committed one differs
  if (Test-Path $Digest) {
    $before = Read-Text $Digest
    Invoke-Digest | Out-Null
    $after = Read-Text $Digest
    if ($before -ne $after) { Warn "digest content was out of date; it has been regenerated" }
    else { Pass "digest content matches BIBLE.md" }
  }
}

# ---------- dispatch ----------
switch ($Command) {
  'digest' { Invoke-Digest }
  'doctor' {
    Invoke-Doctor
    Write-Host ""
    Write-Host "Codex doctor - $($DocsDir):"
    $script:Checks | ForEach-Object { Write-Host $_ }
    Write-Host ""
    Write-Host ("Result: {0} error(s), {1} warning(s)." -f $script:Errors.Count, $script:Warnings.Count)
    if ($script:Errors.Count -gt 0) { exit 1 }
  }
}
