<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>ThinkTank.Core</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MindAttic.Legion" Version="5.0.0" />
        <PackageReference Include="MindAttic.Vault" Version="1.0.0" />
    </ItemGroup>

</Project>
